config: {}
prefecto:
  outputs:
    testing:
      account: account
      authenticator: null
      autocommit: null
      database: null
      password: !!python/object:pydantic.types.SecretStr
        _secret_value: password
      private_key: null
      role: null
      schema: abcdef
      schema_: abc
      threads: 4
      token: null
      type: abc
      user: user
      warehouse: null
  target: testing
