name: Tests

on: [pull_request]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: requirements*.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade --upgrade-strategy eager -e ".[dev]"

      - name: Run unit tests
        env:
          PREFECT_API_DATABASE_CONNECTION_URL: "sqlite+aiosqlite:///./orion-tests.db"
        run: |
          coverage run --branch -m pytest tests -vv -m "not integration"
          coverage report
  run-integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: requirements*.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade --upgrade-strategy eager -e ".[dev]"

      - name: Run integration tests
        env:
          PREFECT_API_DATABASE_CONNECTION_URL: "sqlite+aiosqlite:///./orion-tests.db"
          # Note: our dbt Cloud test account has been cleared out, so we will need to
          # recreate that before we can run the integration tests against the real thing
          # DBT_CLOUD_JOB_ID: ${{ secrets.DBT_CLOUD_JOB_ID }}
          # DBT_CLOUD_ACCOUNT_ID: ${{ secrets.DBT_CLOUD_ACCOUNT_ID }}
          # DBT_CLOUD_API_KEY: ${{ secrets.DBT_CLOUD_API_KEY }}
        run: |
          pytest tests -vv -m integration

      - name: Run mkdocs build
        run: |
          mkdocs build --verbose --clean
